package com.griffinslogistics.db.entities;
// Generated Jul 28, 2014 10:58:21 PM by Hibernate Tools 3.6.0

import com.griffinslogistics.enums.BookspackagePriorityEnum;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.annotations.Formula;

/**
 * Bookspackage generated by hbm2java
 */
public class Bookspackage implements java.io.Serializable {

    private Integer id;
    private Integer version;
    private Transportation transportation;
    private Integer transportationId;
    private TruckGroup truckGroup;
    private String country;
    private String postalCode;
    private String phoneNumber;
    private String email;
    private String packageNumber;
    private String merchant;
    private String client;
    private Double pricePerKilogram;
    private String priority;
    private Date deliveryDate;
    private String deliveryAddress;
    private String remarksSales;
    private String remarksLogistics;
    private String printDeliveryDay;
    private String loadingDay;
    private Set<Book> books;
    private Set boxes = new HashSet(0);
    private List<BookspackageHistory> bookspackageHistories;
    
    private Integer totalBooksCount;
    private Integer totalOrderedBooksCount;
    private Double totalBooksWeight;
    private Double totalOrderedBooksWeight;
    
    private String displayPriority;
    private boolean hasDiscardedBooks;
    
    public Bookspackage() {
    }

    public Bookspackage(Transportation transportation, String packageNumber) {
        this.transportation = transportation;
        this.packageNumber = packageNumber;
    }

    public Bookspackage(Integer id, Integer version, Transportation transportation, TruckGroup truckGroup,
            String country, String postalCode, String phoneNumber, String email, 
            String packageNumber, String merchant, String client, Date deliveryDate,
            String deliveryAddress, String remarks, String printDeliveryDay, Integer totalBooksCount, Integer totalOrderedBooksCount,
            Double totalBooksWeight, Double totalOrderedBooksWeight, String priority, String loadingDay) {
        this.id = id;
        this.version = version;
        this.transportation = transportation;
        this.truckGroup = truckGroup;
        this.country = country;
        this.postalCode = postalCode;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.packageNumber = packageNumber;
        this.merchant = merchant;
        this.client = client;
        this.deliveryDate = deliveryDate;
        this.deliveryAddress = deliveryAddress;
        this.remarksSales = remarks;
        this.printDeliveryDay = printDeliveryDay;
        this.totalBooksCount = totalBooksCount;
        this.totalOrderedBooksCount = totalOrderedBooksCount;
        this.totalBooksWeight = totalBooksWeight;
        this.totalOrderedBooksWeight = totalOrderedBooksWeight;
        this.priority = priority;
        this.loadingDay = loadingDay;
    }
    
    public Bookspackage(Transportation transportation, String packageNumber, String merchant,
            String client, Date deliveryDate, String deliveryAddress, String remarks, String printDeliveryDay,
            Set<Book> books, Set boxes, List<BookspackageHistory> bookspackageHistories) {
        this.transportation = transportation;
        this.packageNumber = packageNumber;
        this.merchant = merchant;
        this.client = client;
        this.deliveryDate = deliveryDate;
        this.deliveryAddress = deliveryAddress;
        this.remarksSales = remarks;
        this.printDeliveryDay = printDeliveryDay;
        this.books = books;
        this.boxes = boxes;
        this.bookspackageHistories = bookspackageHistories;
    }
    
    public Bookspackage makeDeepCopy(){
        Bookspackage bookspackage = new Bookspackage();
        
        bookspackage.setClient(this.getClient());
        bookspackage.setCountry(this.getCountry());
        bookspackage.setDeliveryAddress(this.getDeliveryAddress());
        bookspackage.setDeliveryDate(this.getDeliveryDate());
        bookspackage.setEmail(this.getEmail());
        bookspackage.setMerchant(this.getMerchant());
        bookspackage.setPhoneNumber(this.getPhoneNumber());
        bookspackage.setPostalCode(this.getPostalCode());
        bookspackage.setPrintDeliveryDay(this.getPrintDeliveryDay());
        bookspackage.setRemarksSales(this.getRemarksSales());
        bookspackage.setRemarksLogistics(this.getRemarksLogistics());
        bookspackage.setPriority(this.getPriority());
        
        return bookspackage;
    }
    
    public boolean haveEqualProperties(Bookspackage bookspackage) {
        boolean haveEqualProperties = true;

        haveEqualProperties = haveEqualProperties && this.getClient().equals(bookspackage.getClient());
        haveEqualProperties = haveEqualProperties && this.getCountry().equals(bookspackage.getCountry());
        haveEqualProperties = haveEqualProperties && this.getDeliveryAddress().equals(bookspackage.getDeliveryAddress());
        haveEqualProperties = haveEqualProperties && this.getEmail().equals(bookspackage.getEmail());
        haveEqualProperties = haveEqualProperties && this.getMerchant().equals(bookspackage.getMerchant());
        haveEqualProperties = haveEqualProperties && this.getPhoneNumber().equals(bookspackage.getPhoneNumber());
        haveEqualProperties = haveEqualProperties && this.getPostalCode().equals(bookspackage.getPostalCode());
        haveEqualProperties = haveEqualProperties && this.getRemarksSales().equals(bookspackage.getRemarksSales());
        haveEqualProperties = haveEqualProperties && this.getRemarksLogistics().equals(bookspackage.getRemarksLogistics());
        haveEqualProperties = haveEqualProperties && this.getPrintDeliveryDay().equals(bookspackage.getPrintDeliveryDay());

        TruckGroup existingTruckGroup = this.getTruckGroup();
        TruckGroup bookspackageTruckGroup = bookspackage.getTruckGroup();

        if (existingTruckGroup != null && bookspackageTruckGroup != null) {
            haveEqualProperties = haveEqualProperties && existingTruckGroup.getId().equals(bookspackageTruckGroup.getId());
        } else if (existingTruckGroup == null && bookspackageTruckGroup == null) {
            haveEqualProperties = haveEqualProperties && true;
        } else {
            haveEqualProperties = false;
        }

        Date existingDeliveryDate = this.getDeliveryDate();
        Date bookspackageDeliveryDate = bookspackage.getDeliveryDate();

        if (existingDeliveryDate != null && bookspackageDeliveryDate != null) {
            haveEqualProperties = haveEqualProperties && existingDeliveryDate.equals(bookspackageDeliveryDate);
        } else if (existingDeliveryDate == null && bookspackageDeliveryDate == null) {
            haveEqualProperties = haveEqualProperties && true;
        } else {
            haveEqualProperties = false;
        }

        return haveEqualProperties;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Transportation getTransportation() {
        return this.transportation;
    }

    public void setTransportation(Transportation transportation) {
        this.transportation = transportation;
    }

    public String getPackageNumber() {
        return this.packageNumber;
    }

    public void setPackageNumber(String packageNumber) {
        this.packageNumber = packageNumber;
    }

    public String getMerchant() {
        return this.merchant;
    }

    public void setMerchant(String merchant) {
        this.merchant = merchant;
    }

    public String getClient() {
        return this.client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public Date getDeliveryDate() {
        return this.deliveryDate;
    }

    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    public String getDeliveryAddress() {
        return this.deliveryAddress;
    }

    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    public String getRemarksSales() {
        return this.remarksSales;
    }

    public void setRemarksSales(String remarksSales) {
        this.remarksSales = remarksSales;
    }

    public String getRemarksLogistics() {
        return remarksLogistics;
    }

    public void setRemarksLogistics(String remarksLogistics) {
        this.remarksLogistics = remarksLogistics;
    }

    public Set<Book> getBooks() {
        return this.books;
    }

    public void setBooks(Set<Book> books) {
        this.books = books;
    }

    public Set getBoxes() {
        return this.boxes;
    }

    public void setBoxes(Set boxes) {
        this.boxes = boxes;
    }

    public Integer getTotalBooksCount() {
        return totalBooksCount;
    }

    public void setTotalBooksCount(Integer totalBooksCount) {
        this.totalBooksCount = totalBooksCount;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public TruckGroup getTruckGroup() {
        return truckGroup;
    }

    public void setTruckGroup(TruckGroup truckGroup) {
        this.truckGroup = truckGroup;
    }

    public Integer getTotalOrderedBooksCount() {
        return totalOrderedBooksCount;
    }

    public void setTotalOrderedBooksCount(Integer totalOrderedBooksCount) {
        this.totalOrderedBooksCount = totalOrderedBooksCount;
    }

    public Double getTotalBooksWeight() {
        return totalBooksWeight;
    }

    public void setTotalBooksWeight(Double totalBooksWeight) {
        this.totalBooksWeight = totalBooksWeight;
    }

    public Double getTotalOrderedBooksWeight() {
        return totalOrderedBooksWeight;
    }

    public void setTotalOrderedBooksWeight(Double totalOrderedBooksWeight) {
        this.totalOrderedBooksWeight = totalOrderedBooksWeight;
    }

    public List<BookspackageHistory> getBookspackageHistories() {
        return bookspackageHistories;
    }

    public void setBookspackageHistories(List<BookspackageHistory> bookspackageHistories) {
        this.bookspackageHistories = bookspackageHistories;
    }

    public String getPrintDeliveryDay() {
        return printDeliveryDay;
    }

    public void setPrintDeliveryDay(String printDeliveryDay) {
        this.printDeliveryDay = printDeliveryDay;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
        
        BookspackagePriorityEnum priorityEnum = BookspackagePriorityEnum.byValue(this.priority);
        this.setDisplayPriority(priorityEnum.getDisplayValue());
    }

    public String getDisplayPriority() {
        return displayPriority;
    }

    public void setDisplayPriority(String displayPriority) {
        this.displayPriority = displayPriority;
    }

    public boolean isHasDiscardedBooks() {
        return hasDiscardedBooks;
    }

    public void setHasDiscardedBooks(boolean hasDiscardedBooks) {
        this.hasDiscardedBooks = hasDiscardedBooks;
    }

    public Integer getTransportationId() {
        return transportationId;
    }

    public void setTransportationId(Integer transportationId) {
        this.transportationId = transportationId;
    }

    public Double getPricePerKilogram() {
        return pricePerKilogram;
    }

    public void setPricePerKilogram(Double pricePerKilogram) {
        this.pricePerKilogram = pricePerKilogram;
    }

    public String getLoadingDay() {
        return loadingDay;
    }

    public void setLoadingDay(String loadingDay) {
        this.loadingDay = loadingDay;
    }
}
