package com.griffinslogistics.db.entities;
// Generated Jul 28, 2014 10:58:21 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Deliverydirection generated by hbm2java
 */
public class Deliverydirection implements java.io.Serializable {

    private Integer id;
    private String direction;
    private Set deliveries = new HashSet(0);

    public Deliverydirection() {
    }

    public Deliverydirection(String direction) {
        this.direction = direction;
    }

    public Deliverydirection(String direction, Set deliveries) {
        this.direction = direction;
        this.deliveries = deliveries;
    }

    public Deliverydirection(Integer id, String direction, Set deliveries) {
        this.direction = direction;
        this.id = id;
        this.deliveries = deliveries;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDirection() {
        return this.direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public Set getDeliveries() {
        return this.deliveries;
    }

    public void setDeliveries(Set deliveries) {
        this.deliveries = deliveries;
    }

    @Override
    public boolean equals(Object obj) {

        if (obj instanceof Deliverydirection) {
            return this.getId().equals(((Deliverydirection) obj).getId());

        }
        return false;
    }
}
