package com.griffinslogistics.db.entities;
// Generated Jul 28, 2014 10:58:21 PM by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Transportation generated by hbm2java
 */
public class Transportation  implements java.io.Serializable {


     private Integer id;
     private int weekNumber;
     private int year;
     private Date startDate;
     private Set<Bookspackage> bookspackages = new HashSet<Bookspackage>();
     private Set<Book> books = new HashSet<Book>();
     private List<AdditionalCost> additionalCosts = new ArrayList<AdditionalCost>();

    public Transportation() {
    }

	
    public Transportation(int weekNumber, int year, Date startDate) {
        this.weekNumber = weekNumber;
        this.year = year;
        this.startDate = startDate;
    }
    
    public Transportation(int weekNumber, int year, Date startDate,
            Set<Bookspackage> bookspackages, Set<Book> books, List<AdditionalCost> additionalCosts) {
       this.weekNumber = weekNumber;
       this.year = year;
       this.startDate = startDate;
       this.bookspackages = bookspackages;
       this.books = books;
       this.additionalCosts = additionalCosts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getWeekNumber() {
        return this.weekNumber;
    }
    
    public void setWeekNumber(int weekNumber) {
        this.weekNumber = weekNumber;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    
    public Set<Bookspackage> getBookspackages() {
        return this.bookspackages;
    }
    
    public void setBookspackages(Set<Bookspackage> bookspackages) {
        this.bookspackages = bookspackages;
    }
    
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }

    public List<AdditionalCost> getAdditionalCosts() {
        return additionalCosts;
    }

    public void setAdditionalCosts(List<AdditionalCost> additionalCosts) {
        this.additionalCosts = additionalCosts;
    }
}
