package db;
// Generated Jul 28, 2014 10:58:21 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer id;
     private Bookspackage bookspackage;
     private Transportation transportation;
     private String bookNumber;
     private String title;
     private int count;
     private double weight;
     private Set boxes = new HashSet(0);

    public Book() {
    }

	
    public Book(Bookspackage bookspackage, Transportation transportation, String bookNumber, String title, int count, double weight) {
        this.bookspackage = bookspackage;
        this.transportation = transportation;
        this.bookNumber = bookNumber;
        this.title = title;
        this.count = count;
        this.weight = weight;
    }
    public Book(Bookspackage bookspackage, Transportation transportation, String bookNumber, String title, int count, double weight, Set boxes) {
       this.bookspackage = bookspackage;
       this.transportation = transportation;
       this.bookNumber = bookNumber;
       this.title = title;
       this.count = count;
       this.weight = weight;
       this.boxes = boxes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bookspackage getBookspackage() {
        return this.bookspackage;
    }
    
    public void setBookspackage(Bookspackage bookspackage) {
        this.bookspackage = bookspackage;
    }
    public Transportation getTransportation() {
        return this.transportation;
    }
    
    public void setTransportation(Transportation transportation) {
        this.transportation = transportation;
    }
    public String getBookNumber() {
        return this.bookNumber;
    }
    
    public void setBookNumber(String bookNumber) {
        this.bookNumber = bookNumber;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public double getWeight() {
        return this.weight;
    }
    
    public void setWeight(double weight) {
        this.weight = weight;
    }
    public Set getBoxes() {
        return this.boxes;
    }
    
    public void setBoxes(Set boxes) {
        this.boxes = boxes;
    }




}


