package db;
// Generated Jul 28, 2014 10:58:21 PM by Hibernate Tools 3.6.0



/**
 * Box generated by hbm2java
 */
public class Box  implements java.io.Serializable {


     private Integer id;
     private Bookspackage bookspackage;
     private Book book;
     private int booksCount;
     private int boxesCount;
     
    public Box() {
    }

    public Box(Bookspackage bookspackage, Book book, int booksCount, int boxesCount) {
       this.bookspackage = bookspackage;
       this.book = book;
       this.booksCount = booksCount;
       this.boxesCount = boxesCount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bookspackage getBookspackage() {
        return this.bookspackage;
    }
    
    public void setBookspackage(Bookspackage bookspackage) {
        this.bookspackage = bookspackage;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public int getBooksCount() {
        return this.booksCount;
    }
    
    public void setBooksCount(int booksCount) {
        this.booksCount = booksCount;
    }

    public int getBoxesCount() {
        return boxesCount;
    }

    public void setBoxesCount(int boxesCount) {
        this.boxesCount = boxesCount;
    }




}


