package db;
// Generated Jul 28, 2014 10:58:21 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.Formula;

/**
 * Bookspackage generated by hbm2java
 */
public class Bookspackage implements java.io.Serializable {

    private Integer id;
    private Integer version;
    private Transportation transportation;
    private TruckGroup truckGroup;
    private String country;
    private String postalCode;
    private String phoneNumber;
    private String email;
    private String packageNumber;
    private String merchant;
    private String client;
    private Date deliveryDate;
    private String deliveryAddress;
    private String remarks;
    private Set books = new HashSet(0);
    private Set boxes = new HashSet(0);

//     @Formula("select sum(b.BooksCount * b.BoxesCount) from box b where b.Id = id")
    private Integer totalBooksCount;
    private Integer totalOrderedBooksCount;
    private Double totalBooksWeight;
    private Double totalOrderedBooksWeight;
    
    public Bookspackage() {
    }

    public Bookspackage(Transportation transportation, String packageNumber) {
        this.transportation = transportation;
        this.packageNumber = packageNumber;
    }

    public Bookspackage(Integer id, Integer version, Transportation transportation, TruckGroup truckGroup,
            String country, String postalCode, String phoneNumber, String email, 
            String packageNumber, String merchant, String client, Date deliveryDate,
            String deliveryAddress, String remarks, Integer totalBooksCount, Integer totalOrderedBooksCount,
            Double totalBooksWeight, Double totalOrderedBooksWeight) {
        this.id = id;
        this.version = version;
        this.transportation = transportation;
        this.truckGroup = truckGroup;
        this.country = country;
        this.postalCode = postalCode;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.packageNumber = packageNumber;
        this.merchant = merchant;
        this.client = client;
        this.deliveryDate = deliveryDate;
        this.deliveryAddress = deliveryAddress;
        this.remarks = remarks;
        this.totalBooksCount = totalBooksCount;
        this.totalOrderedBooksCount = totalOrderedBooksCount;
        this.totalBooksWeight = totalBooksWeight;
        this.totalOrderedBooksWeight = totalOrderedBooksWeight;
    }
    
    public Bookspackage(Transportation transportation, String packageNumber, String merchant, String client, Date deliveryDate, String deliveryAddress, String remarks, Set books, Set boxes) {
        this.transportation = transportation;
        this.packageNumber = packageNumber;
        this.merchant = merchant;
        this.client = client;
        this.deliveryDate = deliveryDate;
        this.deliveryAddress = deliveryAddress;
        this.remarks = remarks;
        this.books = books;
        this.boxes = boxes;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Transportation getTransportation() {
        return this.transportation;
    }

    public void setTransportation(Transportation transportation) {
        this.transportation = transportation;
    }

    public String getPackageNumber() {
        return this.packageNumber;
    }

    public void setPackageNumber(String packageNumber) {
        this.packageNumber = packageNumber;
    }

    public String getMerchant() {
        return this.merchant;
    }

    public void setMerchant(String merchant) {
        this.merchant = merchant;
    }

    public String getClient() {
        return this.client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public Date getDeliveryDate() {
        return this.deliveryDate;
    }

    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    public String getDeliveryAddress() {
        return this.deliveryAddress;
    }

    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Set getBooks() {
        return this.books;
    }

    public void setBooks(Set books) {
        this.books = books;
    }

    public Set getBoxes() {
        return this.boxes;
    }

    public void setBoxes(Set boxes) {
        this.boxes = boxes;
    }

    public Integer getTotalBooksCount() {
        return totalBooksCount;
    }

    public void setTotalBooksCount(Integer totalBooksCount) {
        this.totalBooksCount = totalBooksCount;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public TruckGroup getTruckGroup() {
        return truckGroup;
    }

    public void setTruckGroup(TruckGroup truckGroup) {
        this.truckGroup = truckGroup;
    }

    public Integer getTotalOrderedBooksCount() {
        return totalOrderedBooksCount;
    }

    public void setTotalOrderedBooksCount(Integer totalOrderedBooksCount) {
        this.totalOrderedBooksCount = totalOrderedBooksCount;
    }

    public Double getTotalBooksWeight() {
        return totalBooksWeight;
    }

    public void setTotalBooksWeight(Double totalBooksWeight) {
        this.totalBooksWeight = totalBooksWeight;
    }

    public Double getTotalOrderedBooksWeight() {
        return totalOrderedBooksWeight;
    }

    public void setTotalOrderedBooksWeight(Double totalOrderedBooksWeight) {
        this.totalOrderedBooksWeight = totalOrderedBooksWeight;
    }

}
