package db;
// Generated Jul 28, 2014 10:58:21 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer id;
     private Deliverydirection deliverydirection;
     private String requestedBy;
     private String deliveryNumber;
     private Date pickUpDate;
     private Date deliveryDate;
     private String uuid;
     private String state;
     private String volume;
     private BigDecimal weight;
     private String billing;
     private String pickUpAddress;
     private String deliveryAddress;
     private String driver;
     private String executant;
     private BigDecimal priceTaken;
     private BigDecimal priceForUs;
     private String remarks;
     private Set attachments = new HashSet(0);

     private Integer version;
    public Delivery() {
    }

	
    public Delivery(Deliverydirection deliverydirection, String uuid) {
        this.deliverydirection = deliverydirection;
        this.uuid = uuid;
    }
    public Delivery(Deliverydirection deliverydirection, String requestedBy, String deliveryNumber, Date pickUpDate, Date deliveryDate, String uuid, String state, String volume, BigDecimal weight, String billing, String pickUpAddress, String deliveryAddress, String driver, String executant, BigDecimal priceTaken, BigDecimal priceForUs, String remarks, Set attachments, Integer version) {
       this.deliverydirection = deliverydirection;
       this.requestedBy = requestedBy;
       this.deliveryNumber = deliveryNumber;
       this.pickUpDate = pickUpDate;
       this.deliveryDate = deliveryDate;
       this.uuid = uuid;
       this.state = state;
       this.volume = volume;
       this.weight = weight;
       this.billing = billing;
       this.pickUpAddress = pickUpAddress;
       this.deliveryAddress = deliveryAddress;
       this.driver = driver;
       this.executant = executant;
       this.priceTaken = priceTaken;
       this.priceForUs = priceForUs;
       this.remarks = remarks;
       this.attachments = attachments;
       this.version = version;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Deliverydirection getDeliverydirection() {
        return this.deliverydirection;
    }
    
    public void setDeliverydirection(Deliverydirection deliverydirection) {
        this.deliverydirection = deliverydirection;
    }
    public String getRequestedBy() {
        return this.requestedBy;
    }
    
    public void setRequestedBy(String requestedBy) {
        this.requestedBy = requestedBy;
    }
    public String getDeliveryNumber() {
        return this.deliveryNumber;
    }
    
    public void setDeliveryNumber(String deliveryNumber) {
        this.deliveryNumber = deliveryNumber;
    }
    public Date getPickUpDate() {
        return this.pickUpDate;
    }
    
    public void setPickUpDate(Date pickUpDate) {
        this.pickUpDate = pickUpDate;
    }
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getVolume() {
        return this.volume;
    }
    
    public void setVolume(String volume) {
        this.volume = volume;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    public String getBilling() {
        return this.billing;
    }
    
    public void setBilling(String billing) {
        this.billing = billing;
    }
    public String getPickUpAddress() {
        return this.pickUpAddress;
    }
    
    public void setPickUpAddress(String pickUpAddress) {
        this.pickUpAddress = pickUpAddress;
    }
    public String getDeliveryAddress() {
        return this.deliveryAddress;
    }
    
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }
    public String getDriver() {
        return this.driver;
    }
    
    public void setDriver(String driver) {
        this.driver = driver;
    }
    public String getExecutant() {
        return this.executant;
    }
    
    public void setExecutant(String executant) {
        this.executant = executant;
    }
    public BigDecimal getPriceTaken() {
        return this.priceTaken;
    }
    
    public void setPriceTaken(BigDecimal priceTaken) {
        this.priceTaken = priceTaken;
    }
    public BigDecimal getPriceForUs() {
        return this.priceForUs;
    }
    
    public void setPriceForUs(BigDecimal priceForUs) {
        this.priceForUs = priceForUs;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Set getAttachments() {
        return this.attachments;
    }
    
    public void setAttachments(Set attachments) {
        this.attachments = attachments;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    
}


