package db;
// Generated Jul 28, 2014 10:58:21 PM by Hibernate Tools 3.6.0



/**
 * Attachment generated by hbm2java
 */
public class Attachment  implements java.io.Serializable {


     private Integer id;
     private Delivery delivery;
     private String filePath;
     private String contentType;

    public Attachment() {
    }

        public Attachment(String filePath, String contentType) {
        this.filePath = filePath;
        this.contentType = contentType;
    }
    
    public Attachment(Delivery delivery, String filePath, String contentType) {
       this.delivery = delivery;
       this.filePath = filePath;
       this.contentType = contentType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Delivery getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(Delivery delivery) {
        this.delivery = delivery;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public String getContentType() {
        return this.contentType;
    }
    
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getName() {
        int beginIndex = this.filePath.lastIndexOf("/") + 1;
        String name = this.filePath.substring(beginIndex);

        name = name == null ? "" : name;
        
        return name;
    }


}


